name: gis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cupy
  - mamba
  - numpy
  - scipy
  - matplotlib
  - networkx
  - pandas
  - sympy
  - xarray
  - numba
  - dask
  - scikit-learn
  - scikit-image
  - opencv
  - lmoments3
  - ipykernel
  - geopandas
  - rioxarray
  - numba-stats
  - intel-cmplr-lib-rt
  - tbb
  - ipykernel
  - pip:
    - climate-indices
    - pylance