name: gis
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip=23.2.1
  - mamba
  - numpy
  - scipy
  - matplotlib
  - networkx
  - pandas
  - sympy
  - xarray
  - numba
  - dask
  - scikit-learn
  - scikit-image
  - opencv
  - lmoments3
  - ipykernel
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - geopandas
  - rioxarray
  - numba-stats
  - pip:
    - climate-indices
    - pylance